import os
DATADIR = 'data'
W2V_IMG_PATH = os.path.join(DATADIR, 'w2v.png')
W2V_WORDS_PATH = os.path.join(DATADIR, 'w2v_words.json')
W2V_WORDS_ID_PATH = os.path.join(DATADIR, 'w2v_words_id.json')
W2V_EMB_PATH = os.path.join(DATADIR, 'w2v_embeddings.json')
N2N_NATURES_PATH = os.path.join(DATADIR, 'n2n_natures.json')
N2N_NATURES_ID_PATH = os.path.join(DATADIR, 'n2n_natures_id.json')

LABEL_NUM = 2

W2V_EMB_SZ = 512
W2V_BATCH_SZ = 200
W2V_WINDOW_SZ = 5
W2V_SKIP_NUM = 5
W2V_NEG_SAMPLE_NUM = 256
W2V_VISUAL_NUM = 200
W2V_STEP_NUM = 100001

DG_BATCH_SZ = 500
DG_RNUM = 1
DG_TEST_BATCH_SZ = 1
DG_SENTENCE_SZ = 500
DG_TEST_SZ = 500
DG_VALID_SZ = 500
DG_VALID_ARGS = [[DG_BATCH_SZ, DG_RNUM], [300, 0], [200, 3]]

PRE_EMB_SZ = 16
PRE_CONV1_KERNEL_NUM = 3
PRE_CONV1_STRIDE = 1
PRE_POOL1_POOL_SZ = 2
PRE_POOL1_STRIDE = 2
PRE_CONV2_KERNEL_NUM = 4
PRE_CONV2_STRIDE = 1
PRE_POOL2_POOL_SZ = 3
PRE_POOL2_STRIDE = 3
PRE_CONV3_KERNEL_NUM = 5
PRE_CONV3_STRIDE = 1
PRE_POOL3_POOL_SZ = 5
PRE_POOL3_STRIDE = 5
PRE_CONV4_KERNEL_NUM = 6
PRE_CONV4_STRIDE = 1
PRE_CONV1_OUT_D = 30
PRE_CONV_OUT_NUM = 1986
PRE_LSTM_SZ = 24
PRE_LSTM_LAYER_NUM = 1
PRE_LINEAR1_SZ = 16
PRE_LINEAR2_SZ = 24
PRE_LINEAR3_SZ = 2
PRE_E_LEARNING_RATE = 2.0
PRE_E_DECAY_STEP = 5000
PRE_E_DECAY_RATE = 0.05
PRE_G_CUT = 5
PRE_STEP_NUM = 100001
PRE_E_FIXED_RATE = 0.001
PRE_VALID_TIME = 100
